from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from src.artifacts import atomic_write_json, atomic_write_toml, write_config_safely
from src.config import PROJECT_ROOT, load_project_config
from src.market import paths_sha256, sample_heston_numpy
from src.pfhedge_baselines import (
    DETERMINISTIC_MODELS,
    PFHEDGE_VERSION,
    PFHEDGE_WHEEL_SHA256,
    TRAINABLE_MODELS,
)


EXPERIMENT_ROOT = PROJECT_ROOT / "exp" / "PFHedge-Official-v1"
XI_VALUES = (0.1, 0.3)
SEEDS = tuple(range(8))
PUBLIC_SEED = 20_260_724
PUBLIC_PATHS = 100_000
PFHEDGE_REPOSITORY = "https://github.com/pfnet-research/pfhedge"
PFHEDGE_WHEEL = "vendor/pfhedge-0.23.0-py3-none-any.whl"
PFHEDGE_WHEEL_URL = (
    "https://files.pythonhosted.org/packages/c9/d4/2e431b087fac824e04348bb17d496c9121af6d"
    "6979dce1ba04b205b50d4d/pfhedge-0.23.0-py3-none-any.whl"
)

MODEL_METADATA = {
    "black_scholes": {
        "source_class": "pfhedge.nn.BlackScholes",
        "inputs": ["log_moneyness", "time_to_maturity", "volatility"],
        "trainable": False,
    },
    "whalley_wilmott": {
        "source_class": "pfhedge.nn.WhalleyWilmott",
        "inputs": [
            "log_moneyness",
            "time_to_maturity",
            "volatility",
            "previous_hedge",
        ],
        "trainable": False,
    },
    "mlp": {
        "source_class": "pfhedge.nn.MultiLayerPerceptron",
        "inputs": [
            "log_moneyness",
            "time_to_maturity",
            "volatility",
            "previous_hedge",
        ],
        "trainable": True,
        "architecture": "4 hidden ReLU layers of width 32; direct hedge output",
    },
    "ntbn": {
        "source_class": "PFHedge README NoTransactionBandNet",
        "inputs": [
            "log_moneyness",
            "time_to_maturity",
            "volatility",
            "previous_hedge_for_clamp_only",
        ],
        "trainable": True,
        "architecture": (
            "pfhedge.nn.BlackScholes center; pfhedge.nn.MultiLayerPerceptron "
            "4x32 ReLU width net; leaky-ReLU bounds; pfhedge.nn.Clamp"
        ),
    },
}


def _market(base: dict[str, Any], xi: float) -> dict[str, Any]:
    market = dict(base)
    market["xi"] = xi
    return market


def market_name(xi: float) -> str:
    return f"heston-xi{int(round(10 * xi)):02d}"


def _leaderboard(market: dict[str, Any], xi: float) -> dict[str, Any]:
    paths = sample_heston_numpy(market, PUBLIC_PATHS, PUBLIC_SEED)
    return {
        "name": f"pfhedge-official-xi{int(round(10 * xi)):02d}-public",
        "n_paths": PUBLIC_PATHS,
        "seed": PUBLIC_SEED,
        "paths_sha256": paths_sha256(paths),
        "allowed_uses": ["checkpoint_selection", "diagnostic_reporting"],
    }


def _payload(
    project: dict[str, Any],
    *,
    xi: float,
    model_name: str,
    seed: int,
    leaderboard: dict[str, Any],
) -> dict[str, Any]:
    market = _market(project["market"], xi)
    metadata = MODEL_METADATA[model_name]
    return {
        "seed": seed,
        "experiment": {
            "name": "PFHedge-Official-v1",
            "purpose": "official-package baseline under the common Heston protocol",
            "market": market_name(xi),
            "split": "public",
            "model": model_name,
        },
        "market": market,
        "objective": dict(project["objective"]),
        "leaderboard": leaderboard,
        "model": {"name": model_name, **metadata},
        "training": {
            "optimizer": "adam",
            "learning_rate": 1e-3,
            "n_epochs": 10_000,
            "paths_per_epoch": 3_000,
            "validation_interval": 200,
        },
        "evaluation": {
            "leaderboards": ["public"],
            "save_predictions": True,
            "private_access": False,
            "accounting": "project discounted PnL with proportional costs",
        },
        "provenance": {
            "package": "pfhedge",
            "version": PFHEDGE_VERSION,
            "wheel_path": PFHEDGE_WHEEL,
            "wheel_url": PFHEDGE_WHEEL_URL,
            "wheel_sha256": PFHEDGE_WHEEL_SHA256,
            "source_repository": PFHEDGE_REPOSITORY,
            "dependency_install": "hash-verified wheel; uv pip install --no-deps",
            "official_policy_modules_unchanged": True,
            "literal_zero_rate_limitation": (
                "PFHedge BlackScholes and WhalleyWilmott modules use their documented "
                "zero-rate formulas; the common market has r=0.01 and evaluation remains "
                "the project's discounted accounting."
            ),
            "common_protocol_change": (
                "Heston paths are generated by the project and supplied as the four "
                "documented PFHedge state features; trainable models use 10000 updates "
                "x 3000 fresh paths and public checkpoint selection."
            ),
        },
    }


def configs() -> list[tuple[Path, dict[str, Any]]]:
    project = load_project_config()
    result: list[tuple[Path, dict[str, Any]]] = []
    for xi in XI_VALUES:
        market = _market(project["market"], xi)
        leaderboard = _leaderboard(market, xi)
        root = EXPERIMENT_ROOT / market_name(xi) / "public"
        for model_name in sorted(DETERMINISTIC_MODELS):
            directory = root / "deterministic" / model_name
            result.append(
                (
                    directory,
                    _payload(
                        project,
                        xi=xi,
                        model_name=model_name,
                        seed=0,
                        leaderboard=leaderboard,
                    ),
                )
            )
        for seed in SEEDS:
            for model_name in sorted(TRAINABLE_MODELS):
                directory = root / f"seed-{seed:03d}" / model_name
                result.append(
                    (
                        directory,
                        _payload(
                            project,
                            xi=xi,
                            model_name=model_name,
                            seed=seed,
                            leaderboard=leaderboard,
                        ),
                    )
                )
    return result


def generate() -> None:
    generated = configs()
    counts = {"written": 0, "exists": 0}
    for directory, payload in generated:
        directory.mkdir(parents=True, exist_ok=True)
        status = write_config_safely(directory / "config.toml", payload)
        counts[status] += 1

    manifest = {
        "experiment": "PFHedge-Official-v1",
        "n_markets": len(XI_VALUES),
        "n_seeds": len(SEEDS),
        "n_deterministic_configs": len(XI_VALUES) * len(DETERMINISTIC_MODELS),
        "n_trainable_configs": len(XI_VALUES) * len(SEEDS) * len(TRAINABLE_MODELS),
        "n_configs": len(generated),
        "public_seed": PUBLIC_SEED,
        "public_paths": PUBLIC_PATHS,
        "private_access": False,
        "pfhedge_version": PFHEDGE_VERSION,
        "pfhedge_wheel": PFHEDGE_WHEEL,
        "pfhedge_wheel_sha256": PFHEDGE_WHEEL_SHA256,
        "models": sorted(MODEL_METADATA),
        "common_protocol": {
            "market_differences": "xi only",
            "accounting": "discounted",
            "objective": "entropic_risk_gamma_1",
            "transaction_cost": 0.001,
            "n_steps": 30,
            "trainable_budget": "10000 updates x 3000 fresh paths",
            "selection": "minimum public entropic risk",
        },
        "config_directories": [
            str(directory.relative_to(PROJECT_ROOT)) for directory, _ in generated
        ],
    }
    atomic_write_toml(EXPERIMENT_ROOT / "manifest.toml", manifest)
    summary = {"configs": len(generated), **counts}
    atomic_write_json(EXPERIMENT_ROOT / "generation-summary.json", summary)
    print(json.dumps(summary, indent=2))


def main() -> None:
    generate()


if __name__ == "__main__":
    main()
